### ISSUE TITLE
setup eslint

### ISSUE THREAD

**Issue by mahaker** [mahaker/gas-github#1]

**Comment by JohannesFischer** [comment]
I might be able to help. What kind of config were you thinking? Basic `eslint:recommended`, or more specific rules?

Also do you consider tests code that should be linted or `src` only?

**Comment by mahaker** [comment]
Thanks for the comment!

Let's apply only `eslint:recommended`.
I would like to it apply to the test directory too.

**Comment by JohannesFischer** [comment]
Opened a MR adding the basic ESLint setup #4. Please have a look if you have a minute.
